#!/bin/bash

set -euo pipefail

rust-builder-arm() {
    docker build -t build_bot_arm arm-docker
    docker run -v "$HOME/.cargo/git":/root/.cargo/git -v "$HOME/.cargo/registry":/root/.cargo/registry \
	       -v "$(pwd)":/source -t build_bot_arm /bin/bash -c "$@"
}

rust-builder-arm "cargo build --release"
zip -j spotifyd-`date --iso-8601`-armv7.zip target/arm-unknown-linux-gnueabihf/release/spotifyd
